#@ load("@ytt:data", "data")
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: terraform
  labels:
    app: crossplane-provider-terraform
spec:
  args:
    - -d
    - #@ "--poll={}".format(data.values.providerConfig.terraform.poll)
    - #@ "--max-reconcile-rate={}".format(data.values.providerConfig.terraform.maxReconcileRate)
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.17.0
  #@ if hasattr(data.values, "imagePullsecret"):
  packagePullSecrets: 
    - name: #@ data.values.imagePullsecret
  #@ end
  controllerConfigRef:
    name: terraform