apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: ako.platform.ykb.io
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp:
              intoNs: avi-system
          template:
          - helmTemplate:
              name: ako
              namespace: avi-system
              path: config/helm/upstream/ako
              valuesFrom:
              - path: config/helm/values.yaml
          - ytt:
              ignoreUnknownComments: true
              paths:
              - '-'
              - config/carvel
          - kbld: {}
      export:
      - imgpkgBundle:
          image: bgorkemozlu/pkg-ako
          useKbldImagesLock: true
        includePaths:
        - config
