apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: crossplane.platform.ykb.io.1.6.0
spec:
  refName: crossplane.platform.ykb.io
  version: 1.6.0
  releaseNotes:
    The initial release of the crossplane package by wrapping Helm Chart. crossplane Helm chart version is 1.6.0
  valuesSchema:
    openAPIv3:
      title: crossplane.platform.ykb.io
      examples:
      properties:
  template:
    spec:
      deploy:
      - kapp:
          intoNs: crossplane-system
      fetch:
      - git: {}
      template:
      - helmTemplate:
          name: crossplane
          namespace: crossplane-system
          path: config/helm/upstream/crossplane
          valuesFrom:
          - path: config/helm/values.yml
      - ytt:
          ignoreUnknownComments: true
          paths:
          - '-'
          - config/carvel
      - kbld: {}