apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: crossplane.platform.ykb.io
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp:
              intoNs: crossplane-system
          template:
          - helmTemplate:
              name: crossplane
              namespace: crossplane-system
              path: config/helm/upstream/crossplane
              valuesFrom:
              - path: config/helm/values.yaml
          - ytt:
              ignoreUnknownComments: true
              paths:
              - '-'
              - config/carvel
          - kbld: {}
      export:
      - imgpkgBundle:
          image: localhost/docker-local/pkg-crossplane
          useKbldImagesLock: true
        includePaths:
        - config
