apiVersion: v1
kind: Secret
metadata:
  name: ako-values
  namespace: packages
stringData:
  values.yaml: |
    ---
    replicaCount: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: ako-overlay-values
  namespace: packages
stringData:
  patch.yaml: |
    ---
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"ClusterRole", "metadata": {"name": "ako-cr"}})
    ---
    rules:
      #@overlay/match by=overlay.index(0)
      #@overlay/insert after=True
      - apiGroups: ["networking.k8s.io"]
        resources: ["ingressclasses"]
        verbs: ["get","watch","list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: ako-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: ako-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: ako-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: ako-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: ako-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: ako-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ako-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: ako-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: ako-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: ako-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: ako-packages-sa
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ako-overlay-values
  name: ako
  namespace: packages
spec:
  serviceAccountName: ako-packages-sa
  packageRef:
    refName: ako.platform.ykb.io
    versionSelection:
      constraints: 0.0.0+build.1721841247
  values:
  - secretRef:
      name: ako-values