apiVersion: v1
kind: Secret
metadata:
  name: cert-exporter-values
  namespace: packages
stringData:
  values.yaml: |
    ---
    secretsExporter:
      podAnnotations:
        prometheus.io/port: "9793"
        prometheus.io/scrape: "true"
    service:
      create: false
    prometheusServiceMonitor:
      create: false
    prometheusRules:
      create: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-exporter-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-exporter-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-exporter-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-exporter-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-exporter-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-exporter-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-exporter-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-exporter-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-exporter-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-exporter-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-exporter-packages-sa
  name: cert-exporter
  namespace: packages
spec:
  serviceAccountName: cert-exporter-packages-sa
  packageRef:
    refName: cert-exporter.platform.ykb.io
    versionSelection:
      constraints: 0.0.0+build.1726045736
  values:
  - secretRef:
      name: cert-exporter-values
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registrypullsecret
  namespace: packages
spec:
  toNamespace: "*"