apiVersion: v1
kind: Secret
metadata:
  name: crossplane-values
  namespace: packages
stringData:
  values.yaml: |
    ---
    test: gorkem
    providerConfig:
      terraform:
        poll: 10m
        maxReconcileRate: 10
    imagePullsecret: registrypullsecret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: crossplane-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: crossplane-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: crossplane-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: crossplane-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: crossplane-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: crossplane-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: crossplane-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: crossplane-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: crossplane-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: crossplane-packages-sa
  name: crossplane
  namespace: packages
spec:
  serviceAccountName: crossplane-packages-sa
  packageRef:
    refName: crossplane.platform.ykb.io
    versionSelection:
      constraints: 0.0.0+build.1722429660
  values:
  - secretRef:
      name: crossplane-values
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registrypullsecret
  namespace: packages
spec:
  toNamespace: "*"